###########################
## Template config.yml   ##
###########################

# alerts destination #
slack_notification_webhook: <your_slack_webhook_url>

# projects to monitor #
etl_projects:
  - <your_etl_project_path>
