###########################
## Template profiles.yml ##
###########################

## SNOWFLAKE ##
## By default, the tool expects the profile name 'datametry'  ##
## This profile will be used for datametry's outputs. We      ##
## reccomend creating a dedicated database, or at least schema ##
datametry:
  outputs:
    default:
      type: snowflake
      account: [account id]

      ## User/password auth, other options (Keypair/SSO) require other configs ##
      user: [username]
      password: [password]

      role: [user role]
      database: [database name]
      warehouse: [warehouse name]
      schema: [schema name]

      threads: 4
      ## OPTIONAL - if you want to create the lineage based on queries from more
      ## than the last 7 days or you have 10k or more queries in the history pulled during
      ## the requested dates range, add this parameter (NOTE: account_usage requires more permissions, see note below).
      query_history_source: account_usage

## BIGQUERY ##
## By default, the tool expects the profile name 'elementary'  ##
## This profile will be used for elementary's outputs. We      ##
## reccomend creating a dedicated database, or at least schema ##
datametry:
  outputs:
    default:
      type: bigquery

      ## Service account auth, other options require other configs ##
      method: service-account
      keyfile: [full path to your keyfile]

      project: [project id]
      dataset: [dataset name]
      threads: 4
      ## Location is mandatory, can be one of US or EU, or a regional location
      location: [dataset location]
      priority: interactive
